### PR TITLE
Rework corgfbt Model and Redesign Weapon

### PR DESCRIPTION
**Pull request by skymyj**
Tested and work
image

### CODE REVIEW

**Comment by nixtux** [comment]
Sorry but again, commit title is wrong it's not a new model it's a full rework as weapon effect has changed closing issue due to inaccurate title.

**Comment by skymyj** [comment]
I changed Title. you can reopen.
#1469

**Comment by nixtux** [comment]
So now why are we making all the units use the same subset of effects/weapons atm we are loosing originality. This pr with a change in weapon is a no from me.

**Comment by skymyj** [comment]
Well, you are right. 
But TA have so many units and originality. A little less complexity can be good sometimes. 
Imho, the weapon effect atm is uggly.

I can revert weapon anyways.

**Comment by skymyj** [comment]
I merge and if you think need keep weapon, i will add in other merge.
Don't revert it please.

**Pull request merged**
